

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Biblioteka.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class BibliotekaEntities : DbContext
{
    public BibliotekaEntities()
        : base("name=BibliotekaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Autori> Autori { get; set; }

    public virtual DbSet<Clanovi> Clanovi { get; set; }

    public virtual DbSet<IzdanjaKnjiga> IzdanjaKnjiga { get; set; }

    public virtual DbSet<IzdavackeKuce> IzdavackeKuce { get; set; }

    public virtual DbSet<Kategorije> Kategorije { get; set; }

    public virtual DbSet<Knjige> Knjige { get; set; }

    public virtual DbSet<Pozajmice> Pozajmice { get; set; }

    public virtual DbSet<PrimjerciKnjiga> PrimjerciKnjiga { get; set; }


    public virtual ObjectResult<NajnovijaIzdanjaKnjiga_Result> NajnovijaIzdanjaKnjiga(Nullable<int> godina)
    {

        var godinaParameter = godina.HasValue ?
            new ObjectParameter("Godina", godina) :
            new ObjectParameter("Godina", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NajnovijaIzdanjaKnjiga_Result>("NajnovijaIzdanjaKnjiga", godinaParameter);
    }

}

}

