
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Biblioteka.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Knjige
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Knjige()
    {

        this.IzdanjaKnjiga = new HashSet<IzdanjaKnjiga>();

    }


    public int Id { get; set; }

    public string Naslov { get; set; }

    public int AutorId { get; set; }

    public int GodinaOriginala { get; set; }

    public int KategorijaId { get; set; }

    public int BrojNaStanju { get; set; }

    public int BrojIzdatih { get; set; }



    public virtual Autori Autori { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<IzdanjaKnjiga> IzdanjaKnjiga { get; set; }

    public virtual Kategorije Kategorije { get; set; }

}

}
